// Do not edit. This file is machine generated by the Resource DLL Wizard.

library ex01;

{ITE} {DFMFileType} {uprincipal.dfm}
{ITE} {RCFileType} {Win32\Debug\ex01_DRC.rc}

{$R 'uprincipal.dfm' 'Form1:TForm'}
{$R 'Win32\Debug\ex01_DRC.res' 'Win32\Debug\ex01_DRC.rc'}

{$E PTB}

begin
end.
